### ISSUE TITLE
Not clear how to edit settings

### ISSUE THREAD

**Issue by mdrmike** [jpohjolainen/atom-gpg#4]
This is a great addition!  However, it doesn't simply work on a standard Ubuntu setup.  I see in the docs there are settings, but it's not clear where or how to change.  (path to file for example?).  

Before I dig to figure it out, I thought I'd add an issue here.  Most packages have a button for changing [ ![*](http://icons.iconarchive.com/icons/led24.de/led/16/cog-icon.png) **Settings** ] 

In **atom-gpg**, since it doesn't use a standard [ ![*](http://icons.iconarchive.com/icons/led24.de/led/16/cog-icon.png) **Settings** ] button, it's not clear where or how to change configurable settings? Any help in the documentation would be good.  

Although, the best solution IMO, is to include the functionality for a [ ![*](http://icons.iconarchive.com/icons/led24.de/led/16/cog-icon.png) **Settings** ] button.  An example package that has configurable settings is: [Linter](https://github.com/steelbrain/linter).

**Comment by jpohjolainen** [comment]
Maybe something is broken in your setup or things work differently on Ubuntu. For me the settings are where all packages have them: Settings -> Packages -> atom-gpg  and there's Settings button just like other packages.

**Comment by mdrmike** [comment]
I never noticed before but apparently one must reload atom (or OS)?  Because as I check again, I now see a settings button.  awesome.
